'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SchoolEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SchoolEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Course() As DbSet(Of Course)
    Public Property Department() As DbSet(Of Department)
    Public Property OfficeAssignment() As DbSet(Of OfficeAssignment)
    Public Property OnlineCourse() As DbSet(Of OnlineCourse)
    Public Property OnsiteCourse() As DbSet(Of OnsiteCourse)
    Public Property Person() As DbSet(Of Person)
    Public Property StudentGrade() As DbSet(Of StudentGrade)

End Class
